name: Testint-Pipelines
on: workflow_dispatch 
jobs:
  build-step:
    runs-on: ubuntu-latest
    steps: 
      - name: Print greeting
        run: echo "Hello World"
      - name: Print goodbye
        run: echo "Done - Bye"
